productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views  # importamos el archivo llamado views (no creado aún)

urlpatterns = [
    # aquí podemos arrancar la apli cación con una página vacía.
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    # No es necesario poner urls.py, Django ya lo hace
    path('productos/', include('productos.urls'))
]

productos/urls.py
from django.urls import path
# from . significa "la carpeta donde yo me encuentro" queremos ese archivo importado
from . import views

app_name = 'productos'

urlpatterns = [
    path('', views.index, name='index'),  # dejamos un string vacio
    # Creamos una ruta nueva dentro de productos.
    path('formulario', views.formulario, name='formulario'),
    path(
        # Aquí definimos un numero entero para especificar el tipo de dato esperado
        '<int:producto_id>',
        views.detalle,
        name='detalle'
    ),  # dejamos un string vacio
]

productos/models.py
from django.db import models
# Para importar el huso horario para que genere el registro de fecha de creacion de producto
from django.utils import timezone
# Create your models here.


class Categoria(models.Model):
    # Así es como llamamos a un string en el ORM de Django y definimos una longitud máxima.
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    # string con un max de caracteres
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    stock = models.IntegerField()  # numero entero
    puntuacion = models.FloatField()  # numeros decimales
    # Alternativas cuando asignamos una ForeignKey entre campos:
    # CASCADE = elimina el producto si se elmina la categoría.
    # PROTECT = Da un error si queremos eliminar la categoría.
    # RESTRICT = Deja eliminar la categoría cuando no existan productos.
    # SET_NULL = actualiza a valor Nulo en la categoría. Categoría =Null
    # SET_DEFAULT = asigna un valor por defecto

    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE
    )
    # Se le asigna una fecha de creación automática
    creado_en = models.DateTimeField(default=timezone.now)

productos/forms.py
# Importamos desde donde estamos "." los modelos
from . import models
# Importamos el model de formularios
from django.forms import ModelForm

# Creamos una clase igual que el modelo de ProductoForm extiende de ModelForm.


class ProductoForm(ModelForm):
    # A su vez tenemos que agregar otra clase que se llama Meta
    class Meta:
        # Especificar que el modelo viene de productos
        model = models.Producto
        # Aquí metemos una lista con los campos que queremos que tenga el formulario
        fields = ['nombre', 'stock', 'puntuacion', 'categoria']

productly/views.py
from django.shortcuts import render


def inicio(request):
    return render(
        request,
        'inicio.html'
    )

productos/views.py
# Hay que importar esto para las respuestas
# Se añade Http404 para reconocer errores 404 y Redirección al final
from django.http import HttpResponse, HttpResponseRedirect
# Hay que añadir el objeto 404 de error y luego en
from django.shortcuts import render, get_object_or_404
# Con cmd + . nos crea un import de productos.form y ProductoForm
from productos.forms import ProductoForm
from .models import Producto  # Importamos nuestro modelo
# Create your views here.

# /productos (url de productos)

# VAmos a listar un conjunto de elementos mediante el método GET de de SQL


def index(request):  # todas las funciones de vista se llaman index
    productos = Producto.objects.all()
    return render(
        request,  # la funcion encargada de manejar nuestras peticiones y está arriba
        'index.html',  # el siguiente argumento es un string del nombre del archivo de la plantilla
        # hay que indicar los datos de la plantila. Y recibe un diccionario de productos
        context={'productos': productos}
    )


def detalle(request, producto_id):
    # Se puede utlizar pk (PrimaryKey)
    # Aquí llamamos al objeto de producto que sustitye el try and except
    producto = get_object_or_404(Producto, id=producto_id)
    producto = Producto.objects.get(id=producto_id)
    return render(
        request,
        'detalle.html',
        context={'producto': producto}
    )

# Parametros de URL
# def detalle(request, producto_id):
#     return HttpResponse(producto_id)

# Creamos una nueva funcion de formulario


def formulario(request):
    # Añadimos un if para ver si el método del formulario es POST guardar toda la información = formulario
    if request.method == 'POST':
        # Pasarle todo lo que esta en Post (los campos)
        form = ProductoForm(request.POST)
        if form.is_valid():  # Esto es para validar los datos.
            form.save()  # Si es valido lo guardamos y devolverlo a la url de productos.html
            return HttpResponseRedirect('/productos')
    else:  # Si no es una petición de Post, devuelve el formulario de nuevo.
        form = ProductoForm()  # **
    # creamos la instancia del formulario
    # form = ProductoForm()

    return render(
        request,
        'producto_form.html',  # esta es la plantilla que vamos a renderizar
        # pasamos un diccionario y el valor de la variable que acabamos de crear.
        # Asignamos la variable creada más arriba ** (ver asteriscos)
        {'form': form}
    )

productos/templates/detalle.html
{%extends 'base.html'%}

{% block content %}
<div>
    <h6>{{ producto.nombre }}</h6>
    <p>{{ producto.categoria }}</p>
    <p>{{ producto.stock }}</p>
    <p>{{ producto.puntuacion }}</p>
    <p>{{ producto.creado_en }}</p>
</div>

{% endblock %}

productos/templates/form_snippet.html
<!--No hay que extender de base.html, sino que es para que Django vaya renderizando cada campos.
itera todos los campos.Son una especie de lista que se irá iterando cada campo del formulario-->
{% load add_attr %} <!-- Aquí añadimos la carga de poder añadir filtros creados por nosotros-->
{% for field in form %} <!--Iteramos los campos en formulario-->
<div class="mb-3">    
    {{field.label_tag}} <!--{{ field }} <!-esta etiqueta de label_tag es la que se va imprimir y la que aparece en cada campo-->
    {% if field.errors%} <!--Aqui vamos a añadir un if para cuando el usuario cometa errores al introducir datos -->
        {{ field|add_attr: "class:is-invalid" }}
    {% else %}
        {{ field }}
    <div class="invalid-feedback">   
    {% for error in field.errors %}<!--Para iterar los errores usamos otro for dentro-->
        {{ error }}
    {% endfor %}
</div>        
{% endfor %}

productos/templates/index.html
{% extends 'base.html' %} <!--Esto hace que se traiga el archivo base.html-->
{% block content %}
<h1>Productos</h1>
<a href=" {% url 'productos:formulario' %}">Nuevo Producto</a>
<table class="table">
    <thead>
        <th>Nombre</th>
        <th>Stock</th>
        <th>Puntuación</th>
        <th>Categoría</th>
    </thead>


    <tbody>
        {% for producto in productos %} <!--esta es la forma de llamar la BBDD iterando en Django -->
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    <!--Ponemos url + nombre queremos sea link importante '' y luego a donde va a ir el link, en este caso la url con el id-->
                    {{ producto.nombre }}
                </a>
            </td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntuacion }}</td>
            <td>{{ producto.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

productos/templates/producto_form.html
<!--Extendemos el contenido del archivo base.html-->
{% extends 'base.html' %}

{% block content %} 
<!--la web que queremos renderizar es la de formulario que está en productos-->
<form 
    novalidate 
    action="{% url 'productos:formulario' %}" 
    method='post'> <!--novalidate quita advertencias del navegador-->
    {% csrf_token %} <!--Esto es por seguridad. Genera un token por segurdad-->
    {% for field in form %}
    <div>
        {{ field.label_tag }}  <!-- Muestra el nombre del campo -->
        {{ field }}  <!-- Renderiza el input del campo -->
        
        {% if field.errors %}  <!-- Si hay errores, los mostramos -->
            <div style="color: red;">
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    {% endfor %}

    <input type="submit" value="Enviar"/>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Mi Marca de APP</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:index' %}">Productos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container"> <!-- Es una etiqueta de la convención de Django para traernos bloques de Django-->
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/django/forms/label.html
{% if use_tag %}
    <{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">
        {{ label }}
    </{{ tag }}>
{% else %}
    {{ label }}
{% endif %}

templates/django/forms/widgets/input.html
<input
    class="form-control {{ widget.attrs.class}}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"{% if widget.value != None %} 
    value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select select class="form-select"  name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>

templates/inicio.html
{% extends "base.html" %}

{% block content %}

    Hola Mundo, bienvenidos a productly subido al server. Actualizado!!!!!

{% endblock content %}